server:
  port: 8080
  context-path: /uums
spring:
  profiles:
    active: dev
  application:
    name: uums
  datasource:
    url: jdbc:mysql://localhost:3306/uums?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 3000000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
       # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,log4j
       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
security:
    oauth2:
      client:
        client-id: aaaaaa
        client-secret: bbbbbbbb
        access-token-uri: http://openapi.baidu.com/oauth/2.0/token
        user-authorization-uri: http://openapi.baidu.com/oauth/2.0/authorize
      resource:
        user-info-uri: https://openapi.baidu.com/rest/2.0/passport/users/getInfo
#mybatis:
  #configuration:
 # lazy-loading-enabled: true
  #type-aliases-package: com.kjtang.uums.*.entity
  #mapper-locations: classpath:mybatis/**/mapper/*.xml
  #config-location: classpath:mybatis-config.xml
logging:
  level: trace
application:
  debug: true